#!/usr/bin/env python3
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def main():
    root = Path(__file__).resolve().parents[1]
    template = (root / "assets" / "research-report-template.html").read_text(encoding="utf-8")
    now = datetime.now(timezone.utc).isoformat()
    metadata = {
        "question": "Validate whether Research Skill produces machine-readable HTML evidence.",
        "scope": "Forward-test sample only.",
        "depth": "light",
        "generatedAt": now,
    }
    evidence = {
        "claims": [
            {
                "id": "C1",
                "claim": "The report contains embedded JSON evidence blocks.",
                "status": "supported",
                "evidenceIds": ["S1"],
            }
        ],
        "sources": [
            {
                "id": "S1",
                "title": "Local Research HTML Contract",
                "url": "https://example.com/research-html-contract",
                "publisher": "Local sample",
                "version": "sample",
                "accessedAt": now,
            }
        ],
    }
    search_log = {"queries": [], "orchestrationMode": "sync", "warnings": []}
    run_status = {"status": "complete", "recommendation": "accepted", "limitations": []}
    decision_gate = {
        "schemaVersion": "1.0",
        "depth": "light",
        "mode": "fact-check",
        "recommendationStatus": "accepted",
        "rerunResearchRequired": False,
        "riskAcceptanceRequired": False,
        "openCriticalFindings": [],
        "coverageMatrix": [
            {
                "objectType": "claim",
                "objectId": "C1",
                "coverageStatus": "sufficient",
                "evidenceIds": ["S1"],
                "confidenceRationale": "The fixture uses one direct local sample source.",
                "limitations": [],
            }
        ],
        "grillFindingCoverage": [],
    }
    html = (
        template.replace("{{title}}", "Research Skill Forward Test")
        .replace("{{generatedAt}}", now)
        .replace("{{summary}}", "This sample validates the HTML contract.")
        .replace("{{scope}}", "<p>Sample report generated by create_sample_report.py.</p>")
        .replace("{{findings}}", "<ul><li>Embedded JSON blocks are present.</li></ul>")
        .replace(
            "{{evidenceTable}}",
            '<table><tr><th>ID</th><th>Source</th></tr><tr><td>S1</td><td><a href="https://example.com/research-html-contract">Local Research HTML Contract</a></td></tr></table>',
        )
        .replace("{{conflicts}}", "<p>No conflicts in this sample.</p>")
        .replace("{{coverage}}", "<p>One local sample source.</p>")
        .replace("{{security}}", "<p>No external private data used.</p>")
        .replace("{{recommendation}}", "<p>accepted</p>")
        .replace("{{researchMetadataJson}}", json.dumps(metadata, ensure_ascii=False))
        .replace("{{evidenceIndexJson}}", json.dumps(evidence, ensure_ascii=False))
        .replace("{{searchLogJson}}", json.dumps(search_log, ensure_ascii=False))
        .replace("{{runStatusJson}}", json.dumps(run_status, ensure_ascii=False))
        .replace(
            "{{researchDecisionGateJsonBlock}}",
            '<script type="application/json" id="research-decision-gate">'
            + json.dumps(decision_gate, ensure_ascii=False)
            + "</script>",
        )
    )
    if len(sys.argv) > 1:
        out_dir = Path(sys.argv[1]).resolve()
    else:
        out_dir = Path.cwd() / "research-skill-sample-output"
    out_dir.mkdir(exist_ok=True)
    out = out_dir / "research-report.html"
    out.write_text(html, encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
